[package]
name = "peachili"
version = "0.1.0"
authors = ["Drumato <drumatech109@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/", features = ["yaml"] }
yaml-rust = "0.4"